/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mainpackage_CMyClass */

#ifndef _Included_mainpackage_CMyClass
#define _Included_mainpackage_CMyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mainpackage_CMyClass
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_mainpackage_CMyClass_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
